objdet:
  subscribers:

    camera_reading:
      topic: /synth_camera/image_raw
      # topic: /usb_cam/image_raw
      queue_size: 1

  actions:
  
    head_movement:
      enable: false
      topic: /head_controller/point_head_action
      pointing_axis:
        z: 0.80
      frame_id: /map
      pointing_frame: /xtion_rgb_optical_frame
      min_duration:
        s: 1
        ns: 0
      max_velocity: 2.0
    
    enumeration:
      topic: /sciroc_objdet/bridge/enumeration_action

    classification:
      topic: /sciroc_objdet/bridge/classification_action
      
    comparison:
      topic: /sciroc_objdet/bridge/comparison_action
  
  detection:
    display_image: false

    period:
      yolo: 0.1

    threshold:
      yolo: 0.0           # generic
      enumeration: 0.0    # enum mode specific
      classification: 0.0 # clas mode specific
      comparison: 0.0     # comp mode specific

    # choose among: AVG, MODE, MAX
    selection_mode: 
      yolo: AVG           # generic
      enumeration: MODE   # enum mode specific
      classification: MODE # clas mode specific
      comparison: MODE     # comp mode specific

