objdet:
  subscribers:

    camera_reading:
      topic: /synth_camera/image_raw
      # topic: /usb_cam/image_raw
      queue_size: 1

  actions:
  
    head_movement:
      topic: /head_controller/point_head_action
      pointing_frame: /xtion_rgb_optical_frame
      min_duration:
        s: 1
        ns: 0
      max_velocity: 2.0
  
  detection:
    threshold:
      yolo: 0.0
      enumeration: 0.0
      classification: 0.0
      comparison: 0.0